image: gorzechowski/gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - apt install gnupg ca-certificates
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    - apt update
    - apt install -y mono-devel
    - cp -r /usr/include/mono-2.0/* /usr/include
    - chmod +x premake/premake5
    - apt-get update
    - apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev 
    - premake/premake5 gmake
  script:
    - make -j12
  artifacts:
    paths:
      - bin/Debug-linux-x86_64/Sandbox/Sandbox
      - bin/Debug-linux-x86_64/InternalEngine/libInternalEngine.a
