image: gorzechowski/gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - chmod +x premake/premake5
    - apt-get update
    - apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev 
    - premake/premake5 gmake
  script:
    - make -j6
  artifacts:
    paths:
      - bin/Debug-linux-x86_64/Sandbox/Sandbox
      - bin/Debug-linux-x86_64/InternalEngine/libInternalEngine.a